import json

# Load current metadata
with open('songs_metadata.json', 'r', encoding='utf-8') as f:
    songs = json.load(f)

# MapleWordle oldschool songs (extracted from the website)
oldschool_songs = [
    "Above the Treetops",
    "Beachway", 
    "Nightmare",
    "Highland Star",
    "Ancient Remains",
    "Castle Ruins",
    "Water Way",
    "Eregos",
    "When the Morning Comes",
    "Moonlight Shadow",
    "Missing You",
    "Floral Life",
    "Go Picnic",
    "Rest 'N Peace",
    "Cava Bien",
    "Blue Sky",
    "Bad Guys",
    "Jungle Book",
    "Subway",
    "Secret Flower",
    "Sleepywood",
    "Ancient Move",
    "Evil Eyes",
    "Nautilus",
    "Interior of Nautilus",
    "101 Building",
    "101 Building Field",
    "101 Building Subway",
    "Shinin' Harbor",
    "Upon the Sky",
    "Arab Pirate",
    "Come With Me",
    "Tower of a Goddess",
    "Plot of Pixie",
    "Snowy Village",
    "Warm Regard",
    "Wolf Woods",
    "Abandoned Mine",
    "Hell Gate",
    "Mine Quest",
    "Welcome to Hell",
    "Final Fight",
    "Aquarium",
    "Shining Sea",
    "Blue World",
    "Deep Sea",
    "Aqua Cave",
    "Fantastic Thinking",
    "Flying in a Blue Dream",
    "Funny Time Maker",
    "High Enough",
    "Waltz For Work",
    "Wherever You Are",
    "Bizzarre Tales",
    "The Grotesque Way",
    "Timeless",
    "Timeless (B)",
    "Fairy Tale",
    "Fairy Tale (Faster Version)",
    "Fantasia",
    "Dark Shadow",
    "They're Menacing You",
    "Time Attack",
    "Let's March",
    "Let's Hunt Aliens",
    "For the Glory",
    "Finding Forest",
    "Down Town",
    "Dark Mountain",
    "Leafre",
    "Minar's Dream",
    "Ancient Forest",
    "Dragon Load",
    "Dragon's Nest",
    "Cave of Horntail",
    "Horntail",
    "Dragon Rider",
    "Mureung Hill",
    "Mureung Forest",
    "Mu Lung Raid 1",
    "Mu Lung Raid 2",
    "Mu Lung Raid 3",
    "Mu Lung Raid 4",
    "White Herb",
    "Pirate",
    "Ariant",
    "Hot Desert",
    "Fight Sand",
    "Sunset Desert",
    "Dispute",
    "Temple of Time",
    "Rememberance",
    "Repentance",
    "Forgetfulness",
    "Dusk of God",
    "Fighting Pink Bean",
    "Kamuna",
    "Park",
    "Odaiba",
    "Akihabara",
    "Office",
    "Tokyo Sky",
    "New Leaf City - Town",
    "New Leaf City - Hunt",
    "New Leaf City - Upbeat",
    "Phantom Forest (Original)",
    "Crimsonwood Keep",
    "Bigfoot",
    "Crimsonwood Party Quest",
    "Grandmaster's Gauntlet",
    "Crimsonwood Keep Interior",
    "Courtyard",
    "Haunted House",
    "CBD Town",
    "CBD Field",
    "Boat Quay Town",
    "Boat Quay Field",
    "Ghost Ship",
    "Ulu Field",
    "Kuala Lumpur",
    "Highland",
    "Feeling",
    "Bizarre Forest",
    "Castle Trap",
    "Castle Outside",
    "Castle Inside",
    "Castle Boss",
    "Yume",
    "Bathroom",
    "Battlefield",
    "Golden Temple Town",
    "Golden Temple Field",
    "Golden Temple Dungeon",
    "Elin Forest",
    "Poison Forest",
    "First Step Master",
    "Queen's Garden",
    "Raindrop Flower",
    "Drill Hall",
    "Crystal Cave",
    "Rien Village",
    "Snow Drop",
    "Bamboo Gym",
    "Amoria",
    "Cathedral",
    "Chapel",
    "Amorian Challenge"
]

# Add 'oldschool' tag to matching songs
oldschool_count = 0
updated_songs = []

for song in songs:
    # Check if song name matches any oldschool song
    if song['name'] in oldschool_songs:
        song['tags'] = ['oldschool']
        oldschool_count += 1
        print(f"Added 'oldschool' tag to: {song['name']} - {song['regions']['town']}")
    else:
        # Keep existing tags or add empty tags array if none exists
        if 'tags' not in song:
            song['tags'] = []
    
    updated_songs.append(song)

# Save updated metadata
with open('songs_metadata.json', 'w', encoding='utf-8') as f:
    json.dump(updated_songs, f, indent=2, ensure_ascii=False)

print(f"\n✅ Added 'oldschool' tags to {oldschool_count} songs!")
print(f"Total songs in metadata: {len(updated_songs)}")
